package com.company;

import geometries.Cylinder;
import geometries.Plane;
import geometries.Sphere;
import geometries.Triangle;
import primitives.Point3D;
import primitives.Vector;
import primitives.Ray;

/**
 * ************************* *
 *          Targuil 1        *
 *                           *
 *     Netanel COHEN SOLAL   *
 *  netanelcohensolal@me.com *
 *                           *
 *          1444669          *
 *                           *
 *       Yaaccov Chelli      *
 *   yaacovchelly@hotmail.fr *
 *                           *
 *          1382007          *
 * ************************* *
 *
 */
public class Main {

    //Color constantes
    public static final String ANSI_RESET = "\u001B[0m";
    public static final String ANSI_BLUE = "\u001B[34m";
    public static final String ANSI_PURPLE = "\u001B[35m";

    public static void main(String[] args) {


        //Primitives
        Point3D p = new  Point3D(2,5,8);
        Point3D p2 = new Point3D(4,5,90);
        Point3D p1 = new Point3D(8,0,6);

        Vector v = new Vector(2,3,4);
        Vector v1 = new Vector(0,3,4);

        Ray re = new Ray(p,v);

        //Geometries
        Plane pl = new Plane(v,p);
        Cylinder c = new Cylinder(re,p1,p,10);

        Triangle tri = new Triangle(p,p1,p2);
        Triangle tri2 = new Triangle(p1,p,p2); //Same Triangle of tri with the differents point in different fields.

        Sphere sph = new Sphere(p,p1);


        System.out.println(ANSI_PURPLE+"\n------------------------------------------------------------");
        System.out.println("Some Tests in the project :"); //This Will test The classes Coordinates/Point2D/Point3D/Vector
        System.out.println("------------------------------------------------------------"+ANSI_RESET);
        System.out.println('\n');

        System.out.println("------------------------");
        System.out.println("About The vector :"); //This Will test The classes Coordinates/Point2D/Point3D/Vector
        System.out.println("------------------------");
        System.out.println(
                "\nVector  => "+coloredText( v )+"\nVector 1 => "+coloredText( v1 )
                +"\nSize = "+coloredText( v.size() )
                +"\nNormal Vector = "+coloredText( v.getNormalVector() )
                +"\nReverse vector = "+coloredText( v.getReverseVector() )
                +"\nv==v1 ? "+coloredText( v.equals(v1) )
                +"\nv colinear with v1 ? "+coloredText( v.isColinear(v1) )
                +"\nv.v1 = "+coloredText( v.dotProduct(v1) )
                +"\nHead point of v Vector = "+coloredText( v.getHead() )
                +"\nv+v1 = "+coloredText( Vector.add(v,v1) )
                +"\nv-v1 = "+coloredText( Vector.sub(v,v1) )
                +"\nCross product v and v1 = "+coloredText( Vector.crossProdcut(v,v1) )
                +"\nv1*2 = "+coloredText( Vector.mult(v1,2) )

        );
        System.out.println();



        System.out.println("------------------------------------------------------------");
        System.out.println("About The coordinate of the vector :");
        System.out.println("------------------------------------------------------------");
        System.out.println(
                "Distance with the head of vector = "+ coloredText( p.distance(v.getHead()) )
                +"\nAdding v1 to the point = "+coloredText( Point3D.addVector(p,v1) )
                +"\nSubstract v1 to the point = "+coloredText( Point3D.subVector(p,v1) )
        );
        System.out.println();



        System.out.println("------------------------------------------------------------");
        System.out.println("About Plane generated by the 3D point and vector v  :");
        System.out.println("------------------------------------------------------------");
        System.out.println(coloredText( pl ));
        System.out.println();

        //Build the cylinder

        System.out.println("------------------------------------------------------------");
        System.out.println("About Cylinder generated by the 3D point and vector v  :");
        System.out.println("------------------------------------------------------------");
        System.out.println(coloredText( c ));
        System.out.println();


        System.out.println("------------------------------------------------------------");
        System.out.println("About the triangle :");
        System.out.println("------------------------------------------------------------");
        System.out.println(coloredText( tri )+"\n");
        System.out.println("Triangle 1 equals triangles 2 ? "+coloredText(tri.equals(tri2)) );
        System.out.println();


        System.out.println("------------------------------------------------------------");
        System.out.println("About the Sphere :");//p is the the center, p1 the radius
        System.out.println("------------------------------------------------------------");
        System.out.println(coloredText( sph  ));

    }

    public static String coloredText(Object o){
        return ANSI_BLUE+o.toString()+ANSI_RESET;
    }
}
